name: build-and-deploy-test-stable
on:
  push:
    branches:
      - 'master'
      - 'hotfix**'
  workflow_dispatch:
    inputs:
      boolean_input:
        description: 'A boolean input'
        required: true
        type: boolean
        default: false
jobs:
  echoing-job-for-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Echo inputs 
        run: echo "${{ inputs.boolean_input }}"
      - name: Echo inputs 
        run: |
          git config user.name 'whatever'
          git config user.email 'whatever@example.com'
      - name: Echo inputs 
        run: |
          git checkout master
          touch test$(date)
          git add && git commit -m "$(date)"
          git push origin master
