name: build-and-deploy-test-stable
on:
  push:
    branches:
      - 'master'
      - 'hotfix**'
  workflow_dispatch:
    inputs:
      boolean_input:
        description: 'A boolean input'
        required: true
        type: boolean
        default: false
jobs:
  echoing-job-for-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo inputs 
        run: echo "${{ inputs.boolean_input }}"
      - name: Echo inputs 
        run: |
          git config user.name 'whatever'
          git config user.email 'whatever@example.com'

      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Echo inputs
        run: |
          git remote remove origin
          git remote add origin git@github.com:atudomain/github-actions-test.git
          git fetch --all
          git checkout master
          touch test$(date | tr ':' - | tr ' ' _ | tr -d ',')
          git add . && git commit -m "$(date)"
          git push origin master
