name: learn-github-actions
on: 
  push:
    paths:
      - '.github/**'
  workflow_dispatch:
    inputs:
      boolean_input:
        description: 'A boolean input'
        required: true
        type: boolean
        default: false
jobs:
  echoing-job-for-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Echo inputs 
        run: echo "${{ inputs.boolean_input }}"
