name: learn-github-actions
on: 
  push:
    paths:
      - '.github/**'
  workflow_dispatch:
    inputs:
      boolean_input:
        description: 'A boolean input'
        required: true
        type: boolean
        default: false
jobs:
  echoing-job-for-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Echo inputs 
        run: echo "${{ inputs.boolean_input }}"
  failing-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Fail
        run: cat non-existing-file
  some-other-not-dependent-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Echo something 
        run: echo "Something"
  dependant-job:
    runs-on: ubuntu-latest
    needs: failing-job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Echo something
        run: echo "Something"

